package frame

const (
	FRAME_TYPE_PADDING				= 0x00
	FRAME_TYPE_RST_STREAM			= 0x01
	FRAME_TYPE_CONNECTION_CLOSE		= 0x02
	FRAME_TYPE_APPLICATION_CLOSE	= 0x03
	FRAME_TYPE_MAX_DATA				= 0x04
	FRAME_TYPE_MAX_STREAM_DATA		= 0x05
	FRAME_TYPE_MAX_STREAM_ID		= 0x06
	FRAME_TYPE_PING					= 0x07
	FRAME_TYPE_BLOCKED				= 0x08
	FRAME_TYPE_STREAM_BLOCKED		= 0x09
	FRAME_TYPE_STREAM_ID_BLOCKED	= 0x0A
	FRAME_TYPE_NEW_CONNECTION_ID	= 0x0B
	FRAME_TYPE_STOP_SENDING			= 0x0C
	FRAME_TYPE_PONG					= 0x0D
	FRAME_TYPE_ACK					= 0x0E
	FRAME_TYPE_STREAM				= 0x10
	FRAME_TYPE_STREAM_OFF			= 0x14
	FRAME_TYPE_STREAM_LEN			= 0x12
	FRAME_TYPE_STREAM_FIN			= 0x11
)

type Frame struct {
	frameType uint8
}